---
# handlers file for elk_forwarder

- name: restart filebeat
  service:
    name: "filebeat"
    state: restarted
    enabled: yes
  become: yes

- name: restart metricbeat
  service:
    name: "metricbeat"
    state: restarted
    enabled: yes
  become: yes

- name: restart packetbeat
  service:
    name: "packetbeat"
    state: restarted
    enabled: yes
  become: yes

- name: restart auditbeat
  service:
    name: "auditbeat"
    state: restarted
    enabled: yes
  become: yes
